repos:
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.20.0
    hooks:
      - id: markdownlint-cli2
        args: [--fix]
        exclude: |
          (?x)^(
            (.*/)?LICENSE.md |
            openspec/.*\.md
          )$
        verbose: false
  - repo: https://github.com/Cretezy/dart-format-pre-commit
    rev: f728adc8b9ba2b414959cc8beb892e480425cf60
    hooks:
      - id: dart-format
