name: unitary
description: "Unit converter and dimensional analysis calculator"
publish_to: 'none'
version: 0.3.0

environment:
  sdk: ^3.10.8

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  cobertura: ^1.0.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
