name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.x'
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter analyze

  lint-precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.x'
          channel: stable
          cache: true
      - run: flutter pub get
      - uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.x'
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter test --coverage
      - run: dart run cobertura show
      - run: dart run cobertura convert --input coverage/lcov.info --output coverage/cobertura.xml
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/cobertura.xml

  deploy-web:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow --tags
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.x'
          channel: stable
          cache: true
      - run: flutter pub get
      - name: set BUILD_METADATA
        run: |
          BUILD_TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "BUILD_METADATA=${BUILD_TIMESTAMP}.${SHORT_SHA}" >> $GITHUB_ENV
      - run: >-
          flutter build web
          --base-href /unitary/
          --dart-define=BUILD_METADATA=${{ env.BUILD_METADATA }}
          --release
          --wasm
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree build/web add --all
      - shell: bash
        run: |
          git commit -m "Automatic deployment of $(git describe)"
      - run: git push origin HEAD:gh-pages --force
